-- ============================================================
--  EVAD — Bibliothèque partagée : solutions & indicateurs (source de vérité)
--  À exécuter dans le projet Supabase de PROD (lmhhrccmgebztioesmik)
--  → SQL Editor. Généré automatiquement depuis le code (v102).
--
--  L'app lit la bibliothèque au chargement ; si la base est injoignable,
--  elle retombe sur la version embarquée dans le JS. Pour modifier la
--  bibliothèque : Table Editor (les lignes actif=false sont ignorées).
--  Lecture publique, AUCUNE écriture par le front (édition via dashboard).
-- ============================================================

-- Si l'ancienne version « catalogue_ » a déjà été exécutée, on renomme les
-- tables (les données déjà saisies sont conservées). Sans effet sinon.
alter table if exists public.catalogue_solutions rename to biblio_solutions;
alter table if exists public.catalogue_indicateurs rename to biblio_indicateurs;

create table if not exists public.biblio_solutions (
  id          text primary key,
  nom         text not null unique,       -- clé fonctionnelle (référencée partout)
  cat         text,                       -- catégorie (eau, electricite, …)
  cplx        text,                       -- facile | moyen | expert
  img         text,                       -- emoji
  photo       text,                       -- URL illustration
  description text,
  impact      text,                       -- résumé d'impact (affiché en liste)
  budget      text,
  co2         numeric,                    -- tCO2/an évitées
  graines     int default 50,             -- récompense de la quête
  avantages   jsonb,                      -- liste de points forts
  indicateurs_libres jsonb,               -- indicateurs texte (repli)
  esrs        jsonb,                      -- ex. ["ESRS E3"]
  esrs_detail text,
  lieux       jsonb,                      -- types de lieux compatibles
  quete_titre text,                       -- la quête portée par la solution
  quete_duree text,
  quete_nb    text,
  quete_impact text,
  ordre       int,
  actif       boolean default true,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create table if not exists public.biblio_indicateurs (
  id          text primary key,           -- id ICI (ex. eco_co2)
  nom         text not null,
  livre       text,                       -- ecologie | social | economie_locale
  unite       text,
  point0      numeric,                    -- valeur de départ (T0)
  point100    numeric,                    -- référence « excellent » (sous-score 100)
  poids       numeric default 1,
  description text,
  photo       text,                       -- URL illustration
  solution_noms jsonb,                    -- noms des solutions qui portent cet ICI
  odd         jsonb,                      -- correspondances ODD (numéros)
  esrs        jsonb,                      -- correspondances ESRS (codes)
  vsme        jsonb,                      -- correspondances VSME (libellés)
  ordre       int,
  actif       boolean default true,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- Colonne ajoutée après coup (sans effet si déjà présente).
alter table public.biblio_indicateurs add column if not exists photo text;

alter table public.biblio_solutions enable row level security;
alter table public.biblio_indicateurs enable row level security;

-- Lecture publique ; pas de policy d'écriture : le front ne modifie JAMAIS la
-- bibliothèque (édition via le dashboard Supabase, qui contourne la RLS).
drop policy if exists "catalogue_solutions_select" on public.biblio_solutions;
drop policy if exists "catalogue_indicateurs_select" on public.biblio_indicateurs;
drop policy if exists "biblio_solutions_select" on public.biblio_solutions;
create policy "biblio_solutions_select" on public.biblio_solutions for select using (true);
drop policy if exists "biblio_indicateurs_select" on public.biblio_indicateurs;
create policy "biblio_indicateurs_select" on public.biblio_indicateurs for select using (true);

-- ── Seed : bibliothèque actuelle (rejouable : upsert par id) ──
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('recuperation-eau-de-pluie','Récupération eau de pluie','eau','facile','💧','https://images.unsplash.com/photo-1525498128493-380d1990a112?w=800&q=80&auto=format&fit=crop','Système de collecte des eaux pluviales via les gouttières, stockées dans une cuve enterrée ou aérienne (500 à 5 000 L). L''eau récupérée couvre l''arrosage, les sanitaires et le nettoyage, réduisant la consommation d''eau potable de 40 à 60%. Solution simple, sans permis, amortie en 2 à 4 ans selon l''usage.','−18 000 L/an','800–3 500 €',0,50,'["Économie jusqu''à 18 000 L d''eau potable par an","ROI en 2–4 ans, entretien quasi nul","Compatible avec toute toiture et tout type de lieu"]'::jsonb,'["Eau économisée L/an","Autonomie eau %"]'::jsonb,'["ESRS E3"]'::jsonb,'Réduit la consommation d''eau et les rejets, indicateur eau GRI 303.','["ferme","jardin","ecolieu","habitat","tiers","cafe","epicerie","fablab","repair","ressourcerie","coworking","incubateur","ecole","autre"]'::jsonb,'Installer une cuve de récupération','1 journée','3–5 pers.','+8 pts eau · −18 000 L/an',1)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('phytoepuration','Phytoépuration','eau','moyen','🌾','https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&q=80&auto=format&fit=crop','Traitement naturel des eaux grises (vaisselle, douches) par filtration à travers des zones végétales plantées de roseaux, iris et joncs. Élimine 80 à 95 % des polluants organiques sans produit chimique ni énergie. Crée un espace paysager vivant qui valorise les eaux usées en ressource pour le sol.','100% eaux grises traitées','2 500–8 000 €',0.2,70,'["Zéro énergie et zéro consommable chimique","Épure 100 % des eaux grises du site","Double fonction : traitement + espace de biodiversité"]'::jsonb,'["Eaux grises valorisées L/an","Surface végétalisée m²"]'::jsonb,'["ESRS E2","ESRS E3"]'::jsonb,'Supprime les rejets polluants (E2) et valorise la ressource eau (E3).','["ferme","ecolieu","habitat","jardin","tiers"]'::jsonb,'Créer une zone de phytoépuration','2 week-ends','4–8 pers.','+12 pts env. · 100% eaux grises traitées',2)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('toilettes-seches','Toilettes sèches','eau','facile','🌱','https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80&auto=format&fit=crop','Système de WC sans eau : les matières fécales sont couvertes de sciure ou de copeaux et compostées en cuve pendant 12 mois. Économise 6 à 9 litres par chasse, soit 30 000 L par an pour un usage collectif régulier. Le compost produit est utilisable sur les zones non alimentaires du site.','−30 000 L/an','400–2 000 €',0.1,30,'["−30 000 L d''eau potable économisés par an","Produit 100–200 kg de compost exploitable","Installation en 1 journée, sans réseau d''assainissement"]'::jsonb,'["Eau économisée L/an","Compost produit kg/an"]'::jsonb,'["ESRS E3","ESRS E5"]'::jsonb,'Économie d''eau (E3) et valorisation matière organique en circuit fermé (E5).','["ferme","ecolieu","habitat","jardin","tiers","repair","ressourcerie"]'::jsonb,'Installer les toilettes sèches','1 journée','2–4 pers.','+6 pts eau · compost certifiable',3)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('panneaux-solaires-pv','Panneaux solaires PV','electricite','moyen','☀️','https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80&auto=format&fit=crop','Installation de modules photovoltaïques en toiture pour produire de l''électricité directement consommée sur site (autoconsommation) ou réinjectée sur le réseau. Une installation de 6 kWc produit environ 6 000 kWh/an en région tempérée, couvrant 30 à 80 % des besoins selon le profil de consommation. ROI entre 7 et 10 ans, durée de vie 25 à 30 ans.','3 500 kWh/an','6 000–18 000 € (installation 6 kWc)',0.9,90,'["Jusqu''à 80 % d''autonomie électrique en journée","−900 kgCO₂/an évités dès la première année","Valorisable en ESRS E1 pour tout rapport CSRD"]'::jsonb,'["Énergie produite kWh/an","CO₂ évité kgCO2/an"]'::jsonb,'["ESRS E1"]'::jsonb,'Réduction directe des émissions Scope 2, contribue à la trajectoire Net-Zero SBTi.','["ferme","ecolieu","habitat","tiers","fablab","coworking","incubateur","cafe","epicerie","repair","ecole"]'::jsonb,'Chantier participatif d''installation solaire','2 jours','6–10 pers.','+15 pts énergie · −900 kgCO₂/an',4)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('chauffe-eau-solaire','Chauffe-eau solaire','electricite','moyen','🌡','https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=800&q=80&auto=format&fit=crop','Capteurs solaires thermiques installés en toiture qui chauffent l''eau sanitaire via un fluide caloporteur. Couvrent 60 à 80 % des besoins annuels en eau chaude, avec une résistance électrique de complément pour les périodes nuageuses. Solution mature, fiable, avec des aides ANAH et CEE disponibles.','−0.6t CO₂/an','3 000–7 000 € (après aides)',0.6,60,'["60–80 % des besoins eau chaude couverts par le soleil","−600 kgCO₂/an évités sur le poste eau chaude","Aides CEE et MaPrimeRénov'' disponibles"]'::jsonb,'["CO₂ évité kgCO2/an","Autonomie énergie %"]'::jsonb,'["ESRS E1"]'::jsonb,'Décarbonation du poste eau chaude sanitaire, auditable pour le rapport CSRD E1.','["ferme","ecolieu","habitat","tiers","cafe","epicerie"]'::jsonb,'Audit & installation chauffe-eau solaire','1 journée','2–4 pers.','+8 pts énergie · −600 kgCO₂/an',5)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('isolation-paille','Isolation paille','construction','moyen','🏗','https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80&auto=format&fit=crop','Technique de construction biosourcée utilisant des bottes de paille de blé ou de seigle comme isolant dans une ossature bois, recouvertes d''enduit terre-chaux. Réduit les besoins de chauffage de 35 à 50 %. Matériau local à très faible énergie grise, séquestrant du carbone sur toute la durée de vie du bâtiment.','−40% chauffage','80–150 €/m² (hors main-d''œuvre bénévole)',1.2,80,'["−40 % de consommation de chauffage en moyenne","Matériau biosourcé local à énergie grise quasi nulle","Chantier participatif fédérateur (8–15 pers.)"]'::jsonb,'["CO₂ évité kgCO2/an","Énergie produite kWh/an"]'::jsonb,'["ESRS E1","ESRS E5"]'::jsonb,'Matériau biosourcé à faible énergie grise (E5) · forte réduction Scope 1 chauffage (E1).','["ferme","ecolieu","habitat"]'::jsonb,'Chantier d''isolation paille participatif','3 week-ends','8–15 pers.','+20 pts construction · −1,2 tCO₂/an',6)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('toiture-vegetalisee','Toiture végétalisée','construction','moyen','🌿','https://images.unsplash.com/photo-1542621334-a254cf47733d?w=800&q=80&auto=format&fit=crop','Couverture végétale extensive (sedums, graminées) sur toiture plate ou faiblement pentue, sur substrat drainant de 8 à 15 cm. Réduit les besoins de climatisation en été, retient 70 à 80 % des eaux pluviales et crée un habitat pour les pollinisateurs en milieu urbain. Durée de vie de la membrane allongée de 15 à 20 ans.','+biodiversité +isolation','80–200 €/m² (substrat + végétaux + étanchéité)',0.3,65,'["Rétention de 70–80 % des eaux pluviales","−2 à 3 °C en été sous le toit végétalisé","Refuge pour pollinisateurs et oiseaux urbains"]'::jsonb,'["Surface végétalisée m²","Score biodiversité"]'::jsonb,'["ESRS E4","ESRS E3"]'::jsonb,'Favorise la biodiversité urbaine (E4) et la gestion des eaux pluviales (E3).','["tiers","coworking","incubateur","fablab","cafe","epicerie","ecolieu","habitat","ecole"]'::jsonb,'Végétaliser la toiture collective','2 journées','4–6 pers.','+10 pts biodiversité · rétention 80% eaux pluviales',7)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('reemploi-materiaux','Réemploi matériaux','construction','facile','♻️','https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&q=80&auto=format&fit=crop','Pratique consistant à récupérer des matériaux issus de déconstructions (bois, briques, menuiseries, tuiles) pour les réintégrer dans un nouveau chantier. Réduit de 50 à 70 % les coûts de matières premières et divise par deux l''empreinte carbone du chantier. Filière en plein développement avec de nombreuses ressourceries et plateformes locales.','−60% déchets chantier','Économies de 30–60 % vs matériaux neufs',0.8,40,'["−50 à 70 % sur le coût des matériaux","−800 kgCO₂ évités par chantier","Démarche traçable et certifiable ESRS E5"]'::jsonb,'["Déchets détournés kg/an","CO₂ évité kgCO2/an"]'::jsonb,'["ESRS E5"]'::jsonb,'Contribue directement aux indicateurs économie circulaire ESRS E5 (déchets, réemploi).','["fablab","repair","ressourcerie","tiers","ecolieu","ferme","habitat"]'::jsonb,'Organiser un chantier de réemploi','1 journée','3–6 pers.','+10 pts déchets · −800 kgCO₂/chantier',8)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('jardin-permaculture','Jardin permaculture','alimentaire','moyen','🥦','https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&q=80&auto=format&fit=crop','Conception d''un jardin en imitant les écosystèmes naturels : association de plantes compagnes, buttes, guildes d''arbres fruitiers, couverture permanente du sol. Produit en moyenne 200 kg de légumes par an sur 100 m² sans intrants chimiques. Le système devient plus productif et résilient chaque année grâce à l''enrichissement naturel du sol.','~200 kg/an','500–2 000 € (plants, paillage, outils)',0.4,55,'["~200 kg de légumes/an sur 100 m² sans engrais","Sol vivant et de plus en plus fertile chaque saison","Lieu pédagogique et fédérateur pour la communauté"]'::jsonb,'["Production alimentaire kg/an","Autonomie alimentaire %"]'::jsonb,'["ESRS E4","ESRS S3"]'::jsonb,'Soutient la biodiversité locale (E4) et l''alimentation des communautés (S3, impact territorial).','["ferme","jardin","ecolieu","tiers","habitat","ecole"]'::jsonb,'Créer un jardin en permaculture','3 séances','4–10 pers.','+12 pts alimentation · +8 pts biodiversité',9)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('potager-en-buttes','Potager en buttes','alimentaire','facile','🌻','https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=800&q=80&auto=format&fit=crop','Technique de culture sur buttes de bois en décomposition (bois raméal fragmenté, bûches, compost) inspirée de la méthode Hügelkultur. Le bois stocke l''humidité et libère des nutriments sur plusieurs années, réduisant l''arrosage de 60 à 70 %. Idéal pour démarrer rapidement avec peu de moyens sur un sol pauvre.','~80 kg/an','100–400 € (bois récupéré + semences)',0.2,35,'["Arrosage réduit de 60–70 % grâce au bois","Valorise les déchets de bois du site","Mise en place en une journée, productif dès la 1ère saison"]'::jsonb,'["Production alimentaire kg/an","Eau économisée L/an"]'::jsonb,'["ESRS E3","ESRS S3"]'::jsonb,'Réduction de l''irrigation (E3) · production alimentaire locale pour la communauté (S3).','["ferme","jardin","ecolieu","tiers","habitat","ecole"]'::jsonb,'Construire les premières buttes maraîchères','1 journée','3–6 pers.','+6 pts alimentation · −5 000 L eau/an',10)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('compostage-partage','Compostage partagé','dechets','facile','🌍','https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=800&q=80&auto=format&fit=crop','Point de collecte collectif des biodéchets (épluchures, marc de café, restes alimentaires) transformés en compost par décomposition aérobie sur 3 à 6 mois. Détourne 500 à 800 kg de déchets organiques par an de la poubelle grise, produisant 100 à 150 kg de compost mûr utilisable au jardin. Fort levier de sensibilisation et de lien social.','−500 kg déchets/an','200–800 € (composteur collectif + formation)',0.3,30,'["500–800 kg de déchets organiques valorisés par an","100–150 kg de compost gratuit pour le jardin","Action fédératrice : implique toute la communauté du lieu"]'::jsonb,'["Déchets détournés kg/an","Compost produit kg/an"]'::jsonb,'["ESRS E5","ESRS S3"]'::jsonb,'Détournement déchets organiques (E5) · mobilisation de la communauté locale (S3).','["ferme","jardin","ecolieu","tiers","cafe","epicerie","ecole","habitat","coworking","fablab","ressourcerie"]'::jsonb,'Lancer le compostage collectif','2h + suivi mensuel','2–5 pers.','+8 pts déchets · 500 kg/an valorisés',11)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('haie-champetre','Haie champêtre','biodiversite','facile','🌳','https://images.unsplash.com/photo-1490750967868-88df5691cc68?w=800&q=80&auto=format&fit=crop','Plantation d''une haie multi-espèces avec des essences locales (cornouiller, prunellier, aubépine, sureau…) qui accueille nidification, abri et alimentation pour la faune sauvage. Séquestre du carbone, protège des vents dominants et réduit l''érosion des sols. Entretien minimal une fois les arbustes établis après 2 à 3 ans.','+12 espèces','15–40 €/m linéaire (plants + pose)',0.5,45,'["+12 espèces animales accueillies dès la 2ème année","Séquestre 200–500 kg de CO₂/an sur 50 m linéaires","Brise-vent réduisant les besoins de chauffage de 5–10 %"]'::jsonb,'["Score biodiversité","Espèces favorisées nb"]'::jsonb,'["ESRS E4"]'::jsonb,'Indicateur direct ESRS E4, restauration d''écosystèmes, séquestration carbone.','["ferme","jardin","ecolieu","habitat"]'::jsonb,'Planter la haie champêtre','1 journée','4–8 pers.','+15 pts biodiversité · +12 espèces',12)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('mare-ecologique','Mare écologique','biodiversite','moyen','🐸','https://images.unsplash.com/photo-1473621038190-1f1e0fe63ee9?w=800&q=80&auto=format&fit=crop','Création d''un plan d''eau permanent ou temporaire avec berges en pente douce et végétation aquatique locale. Habitat essentiel pour les amphibiens, libellules, oiseaux et insectes pollinisateurs. La mare joue aussi un rôle de régulation hydraulique et de filtration naturelle des eaux de ruissellement du site.','+amphibiens & insectes','800–3 000 € (terrassement + végétalisation)',0.1,60,'["Habitat pour 8+ espèces d''amphibiens et d''insectes","Régule les eaux de ruissellement du site","Aucun entretien après la 1ère saison si bien conçue"]'::jsonb,'["Score biodiversité","Espèces favorisées nb"]'::jsonb,'["ESRS E4","ESRS E3"]'::jsonb,'Restauration d''habitats aquatiques (E4) · gestion naturelle des eaux (E3).','["ferme","jardin","ecolieu","habitat"]'::jsonb,'Creuser et aménager la mare','2 journées','4–6 pers.','+18 pts biodiversité · habitat pour 8+ espèces',13)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('repair-cafe','Repair café','social','facile','🔧','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop','Événement mensuel ouvert à tous où des bénévoles compétents aident les habitants à réparer leurs appareils électroménagers, vêtements, vélos et objets du quotidien. Chaque objet réparé évite en moyenne 4 kg de CO₂. Crée un fort lien social intergénérationnel et valorise les savoir-faire locaux tout en réduisant les déchets.','~200 objets réparés/an','0–500 € (outillage de base)',0.8,35,'["200 objets réparés/an · −800 kgCO₂ évités","Aucun investissement initial, juste de l''espace et des bénévoles","Mobilise 20–50 personnes/mois dans la communauté"]'::jsonb,'["Nb personnes impliquées","Événements collectifs nb/mois"]'::jsonb,'["ESRS E5","ESRS S1","ESRS S3"]'::jsonb,'Économie circulaire (E5) · formation & montée en compétences (S1) · cohésion communautaire (S3).','["fablab","repair","ressourcerie","tiers","cafe","ecole"]'::jsonb,'Organiser le premier Repair Café','1 après-midi/mois','3–8 pers.','+10 pts social · 200 objets/an · −800 kgCO₂',14)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('amap-circuit-court','AMAP circuit court','social','facile','🥕','https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80&auto=format&fit=crop','Association pour le Maintien de l''Agriculture Paysanne : contrat direct entre le lieu et un ou plusieurs agriculteurs locaux qui livrent chaque semaine un panier de saison. Supprime les intermédiaires, garantit un revenu fixe à l''agriculteur et réduit de 60 à 80 % les émissions liées au transport alimentaire. Renforce l''ancrage territorial et la résilience alimentaire du lieu.','90% local','0 € (rémunéré par les adhérents)',0.6,30,'["90 % de l''alimentation d''origine locale et traçable","−60 % d''émissions CO₂ liées au transport des aliments","Garantit un revenu équitable à l''agriculteur partenaire"]'::jsonb,'["Part circuits courts %","Autonomie alimentaire %"]'::jsonb,'["ESRS S2","ESRS S3"]'::jsonb,'Chaîne de valeur locale et équitable (S2) · accès à l''alimentation saine pour la communauté (S3).','["cafe","epicerie","tiers","ecole","coworking","ecolieu","ferme"]'::jsonb,'Monter le partenariat AMAP','2 réunions','2–4 pers.','+12 pts social · 90% approvisionnement local',15)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('toiture-murs-vegetalises','Toiture & murs végétalisés','adaptation','moyen','🪴',null,'Couvrir toits et murs d''une couche végétale (substrat léger + plantes résistantes à la sécheresse) qui isole du chaud comme du froid. La surface abaisse sa température de plusieurs degrés, retient 50 à 80 % des eaux de pluie et crée un refuge de biodiversité. Réduit les besoins de climatisation lors des canicules de plus en plus fréquentes.','−3 à −5 °C en toiture','60–150 €/m²',0.3,80,'["Abaisse la température intérieure de 2 à 4 °C en été","Retient 50–80 % des eaux de pluie, limite le ruissellement","Double l''isolation et accueille la biodiversité"]'::jsonb,'["Surface végétalisée m²","Température de surface évitée °C"]'::jsonb,'["ESRS E1","ESRS E4"]'::jsonb,'Adaptation au changement climatique (E1) et contribution à la biodiversité (E4).','["ecolieu","habitat","tiers","fablab","coworking","incubateur","cafe","epicerie","ecole","autre"]'::jsonb,'Installer une toiture végétalisée','2 week-ends','4–8 pers.','+10 pts adaptation · −3 °C en toiture',16)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('canopee-ilots-de-fraicheur','Canopée & îlots de fraîcheur','adaptation','moyen','🌳',null,'Planter des arbres et arbustes d''ombrage (essences locales adaptées à la sécheresse) pour créer des îlots de fraîcheur. Un arbre mature rafraîchit l''air ambiant par évapotranspiration et par son ombre, jusqu''à 2 à 4 °C ressentis sous le houppier. Protège les espaces extérieurs, les façades et les usagers pendant les vagues de chaleur.','−2 à −4 °C ressentis','30–120 €/arbre',0.6,70,'["Jusqu''à −4 °C ressentis sous les arbres","Stocke du carbone et abrite la biodiversité","Ombre naturelle qui limite la surchauffe des bâtiments"]'::jsonb,'["Arbres plantés","Surface ombragée m²"]'::jsonb,'["ESRS E1","ESRS E4"]'::jsonb,'Adaptation aux fortes chaleurs (E1) et renforcement des écosystèmes (E4).','["ferme","ecolieu","habitat","jardin","tiers","ecole","autre"]'::jsonb,'Planter des arbres d''ombrage','1 journée','5–12 pers.','+9 pts adaptation · îlot de fraîcheur',17)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('ombrieres-pergolas-bioclimatiques','Ombrières & pergolas bioclimatiques','adaptation','facile','⛱️',null,'Installer des structures d''ombrage (pergolas, voiles, ombrières), végétalisées ou couplées à des panneaux solaires, sur les zones exposées : terrasses, façades sud, parkings. Elles bloquent le rayonnement direct, abaissent la température des surfaces et des espaces de vie, et peuvent produire de l''électricité (ombrière photovoltaïque).','−30 à −50 % de soleil direct','150–500 €/m²',0.2,50,'["Réduit de 30 à 50 % le rayonnement solaire direct","Protège façades et terrasses de la surchauffe","Cumulable avec du solaire en ombrière photovoltaïque"]'::jsonb,'["Surface ombragée m²","Énergie solaire produite kWh/an"]'::jsonb,'["ESRS E1"]'::jsonb,'Protection solaire passive, adaptation au réchauffement (E1).','["ecolieu","habitat","tiers","fablab","coworking","cafe","epicerie","ecole","autre"]'::jsonb,'Monter une pergola bioclimatique','1 journée','3–6 pers.','+7 pts adaptation · −30 % ensoleillement',18)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('rafraichissement-passif-du-bati','Rafraîchissement passif du bâti','adaptation','moyen','❄️',null,'Combiner protections solaires (volets, brise-soleil), ventilation nocturne traversante et inertie thermique pour rafraîchir le bâtiment sans climatisation. Un puits canadien (échangeur air-sol) pré-rafraîchit l''air entrant de 4 à 8 °C. Le confort d''été est assuré avec une consommation énergétique quasi nulle, même par +2 °C.','−4 à −6 °C sans clim','2 000–12 000 €',0.4,85,'["Jusqu''à −6 °C en intérieur sans climatisation","Consommation énergétique quasi nulle","Confort d''été durable face aux canicules"]'::jsonb,'["Température intérieure évitée °C","Énergie de clim économisée kWh/an"]'::jsonb,'["ESRS E1"]'::jsonb,'Confort d''été passif, réduit le besoin de climatisation (E1).','["ecolieu","habitat","tiers","fablab","coworking","incubateur","ecole","autre"]'::jsonb,'Audit & rafraîchissement passif','2 jours','3–5 pers.','+12 pts adaptation · −5 °C sans clim',19)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre)
  values ('desimpermeabilisation-des-sols','Désimperméabilisation des sols','adaptation','moyen','💦',null,'Remplacer le bitume et le béton par des sols perméables et végétalisés (stabilisé clair, dalles engazonnées, noues plantées). Les surfaces claires et vivantes stockent moins de chaleur, laissent l''eau s''infiltrer et rafraîchissent l''air par évaporation. Lutte directement contre l''effet d''îlot de chaleur et contre les inondations lors des orages intenses.','−2 °C en surface','40–120 €/m²',0.3,60,'["Réduit l''effet d''îlot de chaleur urbain","Infiltre l''eau de pluie et recharge les nappes","Rafraîchit l''air ambiant par évaporation"]'::jsonb,'["Surface désimperméabilisée m²","Eau infiltrée L/an"]'::jsonb,'["ESRS E1","ESRS E3"]'::jsonb,'Adaptation aux chaleurs et aux pluies intenses (E1), gestion de l''eau (E3).','["ecolieu","habitat","tiers","jardin","ecole","autre"]'::jsonb,'Désimperméabiliser une cour','2 week-ends','5–10 pers.','+8 pts adaptation · sol perméable',20)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre, updated_at=now();

insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_co2','Émissions de CO₂ évitées','ecologie','kg CO₂e/an',0,8000,1,'Le carbone que le lieu n''émet plus grâce à ses solutions : énergie renouvelable, sobriété du bâti, circuits courts et réemploi. C''est l''indicateur climat de référence.','https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80&auto=format&fit=crop','["Panneaux solaires PV","Récupération eau de pluie","Compostage partagé","Réemploi matériaux","Isolation paille","Chauffe-eau solaire","Rafraîchissement passif du bâti"]'::jsonb,'[7,13]'::jsonb,'["E1"]'::jsonb,'["B3 · Énergie & GES"]'::jsonb,1)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_renat','Surface renaturée','ecologie','m²',0,500,1,'Les mètres carrés rendus au vivant : sols cultivés en permaculture, haies, mares, toitures végétalisées, surfaces désimperméabilisées. La base du retour de la biodiversité.','https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80&auto=format&fit=crop','["Jardin permaculture","Potager en buttes","Haie champêtre","Mare écologique","Toiture végétalisée","Désimperméabilisation des sols"]'::jsonb,'[15]'::jsonb,'["E4"]'::jsonb,'["B5 · Biodiversité"]'::jsonb,2)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_eau','Eau potable économisée','ecologie','L/an',0,40000,1,'Les litres d''eau potable que le lieu ne consomme plus : récupération de pluie, traitement des eaux grises, toilettes sans eau. Un enjeu vital en période de sécheresse.','https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=800&q=80&auto=format&fit=crop','["Récupération eau de pluie","Phytoépuration","Toilettes sèches"]'::jsonb,'[6]'::jsonb,'["E3"]'::jsonb,'["B6 · Eau"]'::jsonb,3)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_enr','Énergie renouvelable produite','ecologie','kWh/an',0,12000,1,'L''énergie que le lieu produit lui-même à partir du soleil. Elle mesure le chemin vers l''autonomie énergétique.','https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80&auto=format&fit=crop','["Panneaux solaires PV","Chauffe-eau solaire"]'::jsonb,'[7]'::jsonb,'["E1"]'::jsonb,'["B3 · Énergie & GES"]'::jsonb,4)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_fraicheur','Rafraîchissement obtenu','ecologie','°C en été',0,4,1,'Les degrés gagnés lors des canicules grâce à l''ombre, au végétal et au bâti passif. L''indicateur d''adaptation au changement climatique.','https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80&auto=format&fit=crop','["Canopée & îlots de fraîcheur","Toiture & murs végétalisés","Ombrières & pergolas bioclimatiques","Rafraîchissement passif du bâti","Toiture végétalisée"]'::jsonb,'[11,13]'::jsonb,'["E1"]'::jsonb,'["B3 · Énergie & GES"]'::jsonb,5)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_dechets','Déchets détournés de l''enfouissement','ecologie','kg/an',0,2000,1,'Ce qui ne part plus à la benne : composté, réparé, réemployé. La mesure concrète de l''économie circulaire du lieu.','https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=800&q=80&auto=format&fit=crop','["Compostage partagé","Repair café","Réemploi matériaux","Toilettes sèches"]'::jsonb,'[12]'::jsonb,'["E5"]'::jsonb,'["B7 · Ressources & déchets"]'::jsonb,6)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('soc_insertion','Personnes en insertion accueillies','social','personnes/an',0,12,1,'Les personnes éloignées de l''emploi que le lieu accueille et accompagne à travers ses activités. Le cœur de l''impact d''inclusion.','https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800&q=80&auto=format&fit=crop','["Repair café","AMAP circuit court"]'::jsonb,'[8,10]'::jsonb,'["S1","S3"]'::jsonb,'["B8 · Main-d''œuvre"]'::jsonb,7)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('soc_formation','Heures de formation dispensées','social','heures/an',0,400,1,'Les heures d''apprentissage offertes au territoire : jardinage, réparation, compostage. La transmission des savoir-faire de la transition.','https://images.unsplash.com/photo-1544531586-fde5298cdd40?w=800&q=80&auto=format&fit=crop','["Jardin permaculture","Repair café","Compostage partagé"]'::jsonb,'[4]'::jsonb,'["S1"]'::jsonb,'["B9 · Formation & développement"]'::jsonb,8)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('soc_benevoles','Bénévoles mobilisés','social','personnes/an',0,40,1,'Les habitantes et habitants qui mettent la main à la pâte sur les chantiers participatifs. La vitalité communautaire du lieu.','https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&q=80&auto=format&fit=crop','["Isolation paille","Potager en buttes","Haie champêtre","Mare écologique","Désimperméabilisation des sols"]'::jsonb,'[11,17]'::jsonb,'["S3"]'::jsonb,'["B8 · Main-d''œuvre"]'::jsonb,9)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('soc_sensibilisation','Personnes sensibilisées','social','personnes/an',0,300,1,'Les visiteurs, scolaires et curieux qui découvrent les solutions en fonctionnement. Chaque visite sème une graine ailleurs.','https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop','["Phytoépuration","Toilettes sèches","Mare écologique","Compostage partagé","Canopée & îlots de fraîcheur"]'::jsonb,'[4,13]'::jsonb,'["S3"]'::jsonb,'["B9 · Formation & développement"]'::jsonb,10)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_emplois','Emplois locaux créés','economie_locale','ETP',0,5,1,'Les emplois en équivalent temps plein que l''activité du lieu fait naître sur le territoire. La preuve qu''un lieu régénératif fait vivre.','https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80&auto=format&fit=crop','["AMAP circuit court","Réemploi matériaux"]'::jsonb,'[8]'::jsonb,'["S1","S3"]'::jsonb,'["B8 · Main-d''œuvre"]'::jsonb,11)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_approv','Approvisionnement local','economie_locale','% du budget',20,80,1,'La part du budget du lieu dépensée auprès de producteurs et artisans du territoire. Chaque point gagné irrigue l''économie de proximité.','https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80&auto=format&fit=crop','["AMAP circuit court"]'::jsonb,'[12]'::jsonb,'["S2"]'::jsonb,'["C2 · Chaîne de valeur"]'::jsonb,12)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre)
  values ('eco_biosource','Matériaux biosourcés ou réemployés','economie_locale','tonnes/an',0,10,1,'Les tonnes de paille, bois local et matériaux de seconde vie mis en œuvre à la place du neuf importé. Des filières locales plutôt que des chaînes mondiales.','https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800&q=80&auto=format&fit=crop','["Isolation paille","Réemploi matériaux","Toiture végétalisée","Ombrières & pergolas bioclimatiques"]'::jsonb,'[9,12]'::jsonb,'["E5"]'::jsonb,'["B7 · Ressources & déchets"]'::jsonb,13)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre, updated_at=now();
