-- ============================================================
--  EVAD — 4 nouvelles solutions de la bibliothèque
--    ☕ Café associatif · 🛒 Épicerie participative
--    🫙 Conserverie anti-gaspi · 💻 Réemploi informatique
--  À exécuter dans Supabase PROD (SQL Editor). Idempotent.
--
--  IMPORTANT : la bibliothèque cloud fait foi (hydrateBiblio remplace SOLS).
--  Sans ces lignes en base, les nouvelles solutions disparaîtraient à
--  l'hydratation. Inclut aussi leurs coûts structurés et le rattachement
--  aux indicateurs (biblio_indicateurs.solution_noms).
-- ============================================================

alter table public.biblio_solutions add column if not exists cout_fixe      numeric;
alter table public.biblio_solutions add column if not exists cout_unitaire  numeric;
alter table public.biblio_solutions add column if not exists cout_dimension text;

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,cout_fixe,cout_unitaire,cout_dimension)
  values ('cafe-associatif','Café associatif','social','moyen','☕','https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800&q=80&auto=format&fit=crop','Un café géré par l''association et ses bénévoles : boissons et petite restauration issues de producteurs locaux, prix accessibles, programmation conviviale (concerts, jeux, débats). C''est le cœur battant du lieu : l''endroit où la communauté se croise, où les nouveaux arrivent, et une source de revenus réguliers qui finance le reste du projet.','lieu de vie · 100 % local','2 500–10 000 € (aménagement, équipement, licence)',0.3,60,'["Crée LE point de rencontre du lieu et du quartier","Revenus réguliers réinjectés dans le projet","Approvisionnement 100 % local et de saison"]'::jsonb,'["Nb événements communautaires/mois","% approvisionnement local","Bénévoles mobilisés"]'::jsonb,'["ESRS S3","ESRS S2"]'::jsonb,'Cohésion et vie de la communauté (S3) · chaîne de valeur locale (S2).','["cafe","tiers","ecolieu","epicerie","ecole","autre"]'::jsonb,'Ouvrir le café associatif','4 journées','4–8 pers.','+12 pts social · lieu de vie du quartier',25,2500,30,'usager')
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,cout_fixe=excluded.cout_fixe,cout_unitaire=excluded.cout_unitaire,cout_dimension=excluded.cout_dimension,updated_at=now();

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,cout_fixe,cout_unitaire,cout_dimension)
  values ('epicerie-participative','Épicerie participative','alimentaire','moyen','🛒','https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80&auto=format&fit=crop','Une épicerie gérée par ses membres : chacun donne quelques heures par mois (caisse, réception, rayons) en échange de produits locaux à prix coûtant. L''approvisionnement se fait en direct des producteurs du territoire, sans marge intermédiaire. Le modèle rend l''alimentation de qualité accessible et tisse un lien direct ville-campagne.','~80 % produits locaux','1 500–8 000 € (rayonnages, froid, caisse)',0.4,55,'["Produits locaux 20–40 % moins chers (prix coûtant)","Chaque membre devient acteur du magasin","Revenu direct et équitable pour les producteurs"]'::jsonb,'["Approvisionnement local %","Partenaires locaux","Bénévoles mobilisés"]'::jsonb,'["ESRS S2","ESRS S3"]'::jsonb,'Circuit court équitable (S2) · gouvernance participative et lien social (S3).','["epicerie","tiers","cafe","ecolieu","autre"]'::jsonb,'Monter le rayon vrac & local','2 journées','3–6 pers.','+10 pts éco locale · 80 % local',26,1500,60,'m2')
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,cout_fixe=excluded.cout_fixe,cout_unitaire=excluded.cout_unitaire,cout_dimension=excluded.cout_dimension,updated_at=now();

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,cout_fixe,cout_unitaire,cout_dimension)
  values ('conserverie-anti-gaspi','Conserverie anti-gaspi','alimentaire','moyen','🫙','https://images.unsplash.com/photo-1530062845289-9109b2c9c868?w=800&q=80&auto=format&fit=crop','Transformer les invendus et surplus (du jardin, des producteurs voisins, des marchés) en conserves, jus, soupes et pickles vendus sur place. La cuisine devient un outil anti-gaspillage qui crée de la valeur locale : ce qui allait être jeté devient un produit du lieu, avec des ateliers de transformation ouverts aux habitants.','−800 kg gaspillés/an','2 000–9 000 € (stérilisateur, bocaux, plan de travail)',0.5,55,'["−800 kg de nourriture sauvée de la poubelle par an","Crée une gamme de produits signés du lieu","Ateliers de transformation ouverts aux habitants"]'::jsonb,'["Kg invendus transformés/an","Production locale kg/an","Nb ateliers/mois"]'::jsonb,'["ESRS E5","ESRS S3"]'::jsonb,'Anti-gaspillage, économie circulaire alimentaire (E5) · ateliers ouverts (S3).','["ferme","cafe","epicerie","tiers","ecolieu","autre"]'::jsonb,'Lancer la conserverie anti-gaspi','2 journées','3–6 pers.','+10 pts éco locale · −800 kg gaspillés/an',27,2000,60,'usager')
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,cout_fixe=excluded.cout_fixe,cout_unitaire=excluded.cout_unitaire,cout_dimension=excluded.cout_dimension,updated_at=now();

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,cout_fixe,cout_unitaire,cout_dimension)
  values ('reemploi-informatique','Réemploi informatique','dechets','facile','💻','https://images.unsplash.com/photo-1588508065123-287b28e013da?w=800&q=80&auto=format&fit=crop','Collecter, reconditionner et redistribuer les ordinateurs et équipements numériques dormants du territoire : le lieu s''équipe gratuitement, les habitants accèdent à du matériel fiable à petit prix, et des ateliers d''initiation accompagnent la prise en main. Un ordinateur reconditionné évite ~80 % de l''empreinte carbone d''un neuf.','~300 kg DEEE évités/an','500–3 000 € (outillage, pièces, stockage)',0.6,40,'["Équipe le lieu et les habitants à très bas coût","−300 kg de déchets électroniques par an","Ateliers numériques : personne ne reste au bord du chemin"]'::jsonb,'["Kg DEEE évités/an","Nb équipements reconditionnés","Nb personnes formées"]'::jsonb,'["ESRS E5","ESRS S1","ESRS S3"]'::jsonb,'Réemploi DEEE (E5) · montée en compétences (S1) · inclusion numérique (S3).','["coworking","fablab","tiers","ecole","incubateur","repair","ressourcerie","autre"]'::jsonb,'Organiser une collecte de matériel informatique','1 journée','2–4 pers.','+8 pts déchets · 300 kg DEEE évités',28,800,15,'usager')
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,cout_fixe=excluded.cout_fixe,cout_unitaire=excluded.cout_unitaire,cout_dimension=excluded.cout_dimension,updated_at=now();

-- ── Rattachement aux indicateurs (biblio_indicateurs.solution_noms) ──
-- Ajout idempotent : n'ajoute le nom que s'il n'y est pas déjà.
update public.biblio_indicateurs set solution_noms = solution_noms || '["Café associatif"]'::jsonb
  where id in ('soc_evenements','soc_benevoles','eco_approv') and not solution_noms @> '["Café associatif"]'::jsonb;
update public.biblio_indicateurs set solution_noms = solution_noms || '["Épicerie participative"]'::jsonb
  where id in ('soc_benevoles','eco_approv','eco_partenaires') and not solution_noms @> '["Épicerie participative"]'::jsonb;
update public.biblio_indicateurs set solution_noms = solution_noms || '["Conserverie anti-gaspi"]'::jsonb
  where id in ('eco_dechets','eco_prod_locale','eco_partenaires') and not solution_noms @> '["Conserverie anti-gaspi"]'::jsonb;
update public.biblio_indicateurs set solution_noms = solution_noms || '["Réemploi informatique"]'::jsonb
  where id in ('eco_dechets','soc_formation') and not solution_noms @> '["Réemploi informatique"]'::jsonb;

notify pgrst, 'reload schema';

-- ── Vérification ──
-- select nom, cat, cout_fixe, cout_unitaire, cout_dimension from public.biblio_solutions where ordre >= 25 order by ordre;
-- select id, solution_noms from public.biblio_indicateurs where solution_noms::text like '%Café associatif%';
