-- ============================================================
--  EVAD — Bibliothèque : couverture des 3 capitaux par espace
--  À exécuter dans Supabase PROD (SQL Editor). Idempotent (on conflict).
--  Ajoute 4 solutions (2 sociales, 2 économie locale) + 2 indicateurs,
--  et rattache ces solutions aux indicateurs des bons capitaux.
-- ============================================================

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,actif)
  values ('atelier-de-transmission','Atelier de transmission','social','facile','🎓','https://images.unsplash.com/photo-1544531586-fde5298cdd40?w=800&q=80&auto=format&fit=crop','Ouvrir régulièrement l''espace à des ateliers de transmission des savoir-faire de la transition : jardinage, réparation, cuisine, éco-construction. Les habitants apprennent en faisant, les compétences essaiment sur le territoire et le lieu devient un point de rencontre et d''apprentissage vivant.','~200 h de formation/an','0–1 500 €',0,40,'["Transmet des savoir-faire concrets et réplicables","Crée du lien et fait connaître le lieu au territoire","S''adapte à tout espace : jardin, atelier, cuisine, salle"]'::jsonb,'["Heures de formation h/an","Personnes sensibilisées"]'::jsonb,'["ESRS S1","ESRS S3"]'::jsonb,'Développement des compétences (S1) et lien avec la communauté (S3).','["ferme","jardin","ecolieu","habitat","tiers","cafe","epicerie","fablab","repair","ressourcerie","coworking","incubateur","ecole","autre"]'::jsonb,'Animer un atelier de transmission','1 après-midi','1–3 pers.','+10 pts social · savoir-faire transmis',21,true)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,actif=true,updated_at=now();

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,actif)
  values ('chantier-participatif','Chantier participatif','social','facile','🤝','https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&q=80&auto=format&fit=crop','Mobiliser les habitants sur des chantiers collectifs pour construire, planter ou aménager l''espace. Le faire-ensemble crée de l''appartenance, accueille des personnes en insertion et réalise des aménagements à moindre coût. Chaque chantier est une fête de travail qui ancre le lieu dans sa communauté.','~30 bénévoles/an','0–2 000 €',0,35,'["Mobilise et fédère les habitants autour du lieu","Accueille des personnes éloignées de l''emploi","Réalise des aménagements à faible coût"]'::jsonb,'["Bénévoles mobilisés","Personnes en insertion"]'::jsonb,'["ESRS S1","ESRS S3"]'::jsonb,'Inclusion et insertion (S1) · engagement de la communauté (S3).','["ferme","jardin","ecolieu","habitat","tiers","cafe","epicerie","fablab","repair","ressourcerie","coworking","incubateur","ecole","autre"]'::jsonb,'Organiser un chantier participatif','1 journée','6–15 pers.','+12 pts social · chantier collectif',22,true)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,actif=true,updated_at=now();

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,actif)
  values ('approvisionnement-local','Approvisionnement local','alimentaire','facile','🧺','https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80&auto=format&fit=crop','Réorienter les achats du lieu (alimentation, fournitures, matériaux) vers des producteurs et artisans du territoire. On cartographie les fournisseurs de proximité, on contractualise et on mesure la part locale du budget. Chaque euro dépensé localement fait vivre l''économie de proximité plutôt que des chaînes mondiales.','~70 % achats locaux','0 € (réorientation d''achats)',0.4,30,'["Fait vivre les producteurs et artisans du territoire","Réduit l''empreinte carbone du transport","Renforce la résilience et l''ancrage local du lieu"]'::jsonb,'["Approvisionnement local %","Partenaires locaux"]'::jsonb,'["ESRS S2"]'::jsonb,'Chaîne de valeur locale et équitable (S2).','["ferme","jardin","ecolieu","habitat","tiers","cafe","epicerie","fablab","repair","ressourcerie","coworking","incubateur","ecole","autre"]'::jsonb,'Référencer les producteurs locaux','2 réunions','2–4 pers.','+10 pts éco locale · circuit court',23,true)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,actif=true,updated_at=now();

insert into public.biblio_solutions (id,nom,cat,cplx,img,photo,description,impact,budget,co2,graines,avantages,indicateurs_libres,esrs,esrs_detail,lieux,quete_titre,quete_duree,quete_nb,quete_impact,ordre,actif)
  values ('recyclerie-reemploi-local','Recyclerie & réemploi local','dechets','moyen','🛍️','https://images.unsplash.com/photo-1489274495757-95c7c837b101?w=800&q=80&auto=format&fit=crop','Ouvrir un point de collecte, réparation et revente d''objets et matériaux de seconde main. Ce qui était déchet devient ressource et emploi local : mobilier, textile, matériaux. La recyclerie crée des postes en insertion, alimente les chantiers du territoire en matériaux de réemploi et détourne des tonnes de l''enfouissement.','~3 t réemployées/an','3 000–15 000 €',0.9,45,'["Détourne plusieurs tonnes de déchets par an","Crée des emplois locaux et de l''insertion","Fournit des matériaux de réemploi au territoire"]'::jsonb,'["Matériaux réemployés t/an","Emplois locaux ETP","Partenaires locaux"]'::jsonb,'["ESRS E5","ESRS S1"]'::jsonb,'Économie circulaire (E5) et emploi/insertion locale (S1).','["tiers","ecolieu","fablab","repair","ressourcerie","cafe","epicerie","coworking","incubateur","ecole","autre"]'::jsonb,'Lancer un point de réemploi','3 week-ends','4–8 pers.','+12 pts éco locale · réemploi',24,true)
  on conflict (id) do update set nom=excluded.nom,cat=excluded.cat,cplx=excluded.cplx,img=excluded.img,photo=excluded.photo,description=excluded.description,impact=excluded.impact,budget=excluded.budget,co2=excluded.co2,graines=excluded.graines,avantages=excluded.avantages,indicateurs_libres=excluded.indicateurs_libres,esrs=excluded.esrs,esrs_detail=excluded.esrs_detail,lieux=excluded.lieux,quete_titre=excluded.quete_titre,quete_duree=excluded.quete_duree,quete_nb=excluded.quete_nb,quete_impact=excluded.quete_impact,ordre=excluded.ordre,actif=true,updated_at=now();

insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre,actif)
  values ('soc_evenements','Événements ouverts organisés','social','événements/an',0,24,1,'Les ateliers, chantiers participatifs et rencontres ouverts au territoire. Ce qui fait d''un lieu un espace vivant et partagé.','https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80&auto=format&fit=crop','["Atelier de transmission","Chantier participatif","Repair café"]'::jsonb,'[11,17]'::jsonb,'["S3"]'::jsonb,'["B8 · Main-d''œuvre"]'::jsonb,11,true)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre,actif=true,updated_at=now();

insert into public.biblio_indicateurs (id,nom,livre,unite,point0,point100,poids,description,photo,solution_noms,odd,esrs,vsme,ordre,actif)
  values ('eco_partenaires','Partenaires locaux mobilisés','economie_locale','partenaires',0,20,1,'Les producteurs, artisans et associations du territoire avec qui le lieu tisse des liens durables. Le maillage de l''économie de proximité.','https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80&auto=format&fit=crop','["Approvisionnement local","Recyclerie & réemploi local","AMAP circuit court"]'::jsonb,'[8,17]'::jsonb,'["S2"]'::jsonb,'["C2 · Chaîne de valeur"]'::jsonb,14,true)
  on conflict (id) do update set nom=excluded.nom,livre=excluded.livre,unite=excluded.unite,point0=excluded.point0,point100=excluded.point100,poids=excluded.poids,description=excluded.description,photo=excluded.photo,solution_noms=excluded.solution_noms,odd=excluded.odd,esrs=excluded.esrs,vsme=excluded.vsme,ordre=excluded.ordre,actif=true,updated_at=now();

-- Rattachement des nouvelles solutions aux indicateurs existants
update public.biblio_indicateurs set solution_noms='["Jardin permaculture","Repair café","Compostage partagé","Atelier de transmission"]'::jsonb, updated_at=now() where id='soc_formation';
update public.biblio_indicateurs set solution_noms='["Isolation paille","Potager en buttes","Haie champêtre","Mare écologique","Désimperméabilisation des sols","Chantier participatif"]'::jsonb, updated_at=now() where id='soc_benevoles';
update public.biblio_indicateurs set solution_noms='["Phytoépuration","Toilettes sèches","Mare écologique","Compostage partagé","Canopée & îlots de fraîcheur","Atelier de transmission"]'::jsonb, updated_at=now() where id='soc_sensibilisation';
update public.biblio_indicateurs set solution_noms='["AMAP circuit court","Réemploi matériaux","Approvisionnement local","Recyclerie & réemploi local"]'::jsonb, updated_at=now() where id='eco_emplois';
update public.biblio_indicateurs set solution_noms='["AMAP circuit court","Approvisionnement local"]'::jsonb, updated_at=now() where id='eco_approv';
update public.biblio_indicateurs set solution_noms='["Isolation paille","Réemploi matériaux","Toiture végétalisée","Ombrières & pergolas bioclimatiques","Recyclerie & réemploi local"]'::jsonb, updated_at=now() where id='eco_biosource';
